---
title: "Assign taxonomy to MED nodes"
author: "Hans Schrieke and Julie Reveillaud"
date: "`r Sys.Date()`"
output: 
  rmdformats::readthedown:
    lightbox: true
    gallery: false
    fig_caption: true
    highlight: tango
    toc_depth: 3
    code_folding: "show"
---


# Paths and libraries setting

```{r, warning=FALSE, message=FALSE}
# load packages
packages <- c("tidyverse", "ggplot2", "Biostrings", "dada2")
invisible(lapply(packages, require, character.only = TRUE))

# create output folders if needed
if (!dir.exists("../../../output/1_MED/1B")) {dir.create("../../../output/1_MED/1B")}
```

# Import fasta file
```{r warning=FALSE}
# import fasta files from MED
fasta <- readDNAStringSet("../../../output/1_MED/1A/1A_MED_sequences-m0.10-A0-M0-d4/NODE-REPRESENTATIVES.fasta")
fasta_df <- fasta %>% as.data.frame()

# remove gaps
fasta_df$x <- fasta_df$x %>% gsub(pattern = "-", replacement = "")
```

# Read distribution in samples
```{r warning=FALSE}
read_distribution <- read.table("../../../output/1_MED/1A/1A_MED_sequences-m0.10-A0-M0-d4/READ-DISTRIBUTION.txt", header=TRUE)
read_distribution$samples <- factor(read_distribution$samples, levels = read_distribution$samples[order(read_distribution$represented_reads)])

ggplot(read_distribution, aes(x=samples, y=represented_reads))+
  geom_bar(stat="identity")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  labs(x="Sample", y="Number of read")+
  geom_text(aes(label=represented_reads), position=position_dodge(width=0.5), size=2, hjust=-0.25, vjust=0.25, angle=90)
```

# Taxonomic assignment on MED nodes

```{r warning=FALSE}
set.seed(102)
taxo <- assignTaxonomy(fasta_df$x, "../../../bank/silva_nr99_v138_train_set.fa.gz",
                            multithread=TRUE, minBoot = 80)

# add species
taxo <- addSpecies(taxo, "../../../bank/silva_species_assignment_v138.fa")
```

# Distribution by Genus
```{r warning=FALSE}
seqtab <- taxo %>% as.data.frame()
df <- table(seqtab$Genus) %>% as.data.frame()

ggplot(df, aes(x=as.factor(Var1), y=Freq))+
  geom_bar(stat="identity")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  labs(x="Genus", y="Number of MED node")
```

# Save tax table
```{r warning=FALSE}
write.table(taxo, "../../../output/1_MED/1B/1B_MED_nodes_taxo.tsv", sep="\t")
```

# Session info
```{r warning=FALSE, message=FALSE}
sessionInfo()
```
