---
title: "Merge raw data"
author: "Hans Schrieke and Julie Reveillaud"
date: "`r Sys.Date()`"
output: 
  rmdformats::readthedown:
    lightbox: true
    gallery: false
    fig_caption: true
    highlight: tango
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Paths and libraries setting
```{r, warning=FALSE, message=FALSE}

# libraries
require(tidyverse)
require(kableExtra)

# # paths
# path_main <- "/Volumes/MY_PASSPORT/draft_final"
# path_output <- paste0(path_main, "/output/0_useful_files")

# Load main packages
source("../../source/paths.R")
```


# Generate R1 and R2 sample files

```{r engine='bash', comment=''}
source /Volumes/MY_PASSPORT/draft_final/script/source/paths_bash.sh

# print script to generate samples files for R1 and R2
cat $PATH_MERGE_SCRIPT/generate_R1_R2_files.sh

# run
bash $PATH_MERGE_SCRIPT/generate_R1_R2_files.sh
```


# Generate a main sample file

```{r engine='bash', warning=FALSE, message=FALSE}
source /Volumes/MY_PASSPORT/draft_final/script/source/paths_bash.sh

# create a sample file txt
Rscript $PATH_MERGE_SCRIPT/create_sample_file.R
```

```{r warning=FALSE, message=FALSE}
setwd(paste0(path_output, "/0_useful_files"))

# print
df <- read.table("0_sample_file.txt", header = TRUE)

df %>%
  kbl(booktable=TRUE) %>%
  kable_paper("hover", full_width = F)

```

# Merge samples

```{r engine='bash'}
source /Volumes/MY_PASSPORT/draft_final/script/source/paths_bash.sh

bash $PATH_MERGE_SCRIPT/make_merge.sh
```

```{r engine='r'}
setwd(path_merge)
list.files() %>% cat(sep="\n")
```

