---
title: "Taxonomic analysis"
author: "Hans Schrieke and Julie Reveillaud"
date: "`r Sys.Date()`"
output: 
  rmdformats::readthedown:
    lightbox: true
    gallery: false
    fig_caption: true
    highlight: tango
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparation

## Paths and libraries setting
```{r, warning=FALSE, message=FALSE}
# Load main packages, paths and custom functions
source("../../../source/main_packages.R")
source("../../../source/functions.R")

# Load supplementary packages
packages <- c("RColorBrewer", "ggpubr", "cowplot")
invisible(lapply(packages, require, character.only = TRUE))
```

## Load phyloseq object after decontam
```{r warning=FALSE}
ps.filter <- readRDS("../../../../output/1_MED/1D/1D_MED_phyloseq_decontam.rds")
```

## Setting plot display
```{r warning=FALSE}
# select whole
ps.filter.whole <- subset_samples(ps.filter, Organ=="Whole")
ps.filter.whole <- prune_taxa(taxa_sums(ps.filter.whole) >= 1, ps.filter.whole)
ps.filter.whole <- prune_samples(sample_sums(ps.filter.whole) >= 1, ps.filter.whole)
ps.filter.whole

# select ovary
ps.filter.ovary <- subset_samples(ps.filter, Organ=="Ovary")
ps.filter.ovary <- prune_taxa(taxa_sums(ps.filter.ovary) >= 1, ps.filter.ovary)
ps.filter.ovary <- prune_samples(sample_sums(ps.filter.ovary) >= 1, ps.filter.ovary)
ps.filter.ovary

# col for whole
col_w <- c("N0711.Wolbachia"="#FEB24C",
         "N0241.Wolbachia"="#FAD769",
         "N0720.Wolbachia"="#E09025",
         "N0447.Asaia"="#10E015",
         "N0939.Asaia"="#A6DE45",
         "N1147.Asaia"="#CDDE8E",
         "N1156.Asaia"="#DDFFC4",
         "N0989.Elizabethkingia"="#66A7ED",
         "N0990.Elizabethkingia"="#6AC3F7",
         "N0991.Elizabethkingia"="#6AEEF7",
         "N1160.Elizabethkingia"="#AEC8F5",
         "N1030.Chryseobacterium"="#F899FF",
         "N1034.Chryseobacterium"="#FFB6ED",
         "N1035.Chryseobacterium"="#F5D0E5",
         "N0635.Legionella"="#DE3F23",
         "N1065.Legionella"="#FF7D5E",
         "N1068.Legionella"="#FEB9AD",
         "N0311.Erwinia"="#FFE352",
         "N0798.Erwinia"="#FFFFCF",
         "N0802.Erwinia"="#F5F61B",
         "N1114.Serratia"="#B136F5",
         "N1116.Serratia"="#B863FF",
         "N0313.Morganella"="#F5E4D3",
         "N0846.Pseudomonas"="#DBF5F0",
         "N0318.NA"="grey",
         "Other"="#A0A0A0")

# col for ovary
col_o <- c("N0711.Wolbachia"="#FEB24C",
         "N0241.Wolbachia"="#FAD769",
         "N0720.Wolbachia"="#E09025",
         "N0013.Wolbachia"="#7FC97F", 
         "N0019.Wolbachia"="brown",
         "N0026.Wolbachia"="#BEAED4",
         "N0044.Wolbachia"="#FDC086",
         "N0054.Wolbachia"="#FFFF99",
         "N0240.Wolbachia"="#386CB0",
         "N0242.Wolbachia"="#F0027F",
         "N0244.Wolbachia"="#BF5B17",
         "N0245.Wolbachia"="#666666",
         "N0249.Wolbachia"="#B3E2CD",
         "N0250.Wolbachia"="#FDCDAC",
         "N0251.Wolbachia"="#CBD5E8",
         "N0253.Wolbachia"="#F4CAE4",
         "N0712.Wolbachia"="#E6F5C9",
         "N0713.Wolbachia"="#FFF2AE",
         "N0714.Wolbachia"="#F1E2CC",
         "N0715.Wolbachia"="#CCCCCC",
         "N0447.Asaia"="#10E015",
         "N0939.Asaia"="#A6DE45",
         "N1147.Asaia"="#CDDE8E",
         "N1156.Asaia"="#DDFFC4",
         "N0022.Delftia"="#C7C5B7",
         "Other"="#A0A0A0"
)

# param for plot
guide_italics <- guides(fill = guide_legend(label.theme = element_text(size = 10, face = "italic", colour = "Black", angle = 0)))
```

# Taxonomic structure plots

## Whole (the 15 most abundant nodes)
```{r fig.height = 12, fig.width=14}
# data pour plot
data_for_plot <- taxo_data (ps.filter.whole, top=15)
paste0("\n15 MOST ABUNDANT GENUS: \n") %>% cat()
paste0("\"", levels(data_for_plot$Name), "\",\n") %>% cat()

new_names_15_w <- c("N0711.Wolbachia",
               "N0939.Asaia",
               "N1147.Asaia",
               "N1156.Asaia",
               "N0990.Elizabethkingia",
               "N1160.Elizabethkingia",
               "N1034.Chryseobacterium",
               "N1035.Chryseobacterium",
               "N0635.Legionella",
               "N1065.Legionella",
               "N0311.Erwinia",
               "N0798.Erwinia",
               "N0313.Morganella",
               "N0846.Pseudomonas",
               "N0318.NA",
               "Other")

data_for_plot$Name <- factor(data_for_plot$Name, levels = new_names_15_w)

make.italic <- function(x) as.expression(lapply(x, function(y) bquote(italic(.(y)))))

levels(data_for_plot$Species.x)= c("Aedes aegypti"=make.italic("Aedes aegypti"),
               "Culex pipiens"=make.italic("Culex pipiens"),
               "Culex quinquefasciatus"=make.italic("Culex quinquefasciatus"))

levels(data_for_plot$Strain) <- c("Field - Bosc", 
                                  "Field~-~Camping~Europe", 
                                  "Field~-~Guadeloupe", 
                                  "Laboratory~-~Lavar", 
                                  expression(paste("Laboratory - Slab TC (", italic("Wolbachia"), "-)")))

p <- ggplot(data_for_plot, aes(x = Sample, y = Relative_Abundance, fill = Name, species=Species.x, organ=Organ, Strain=Strain))+ 
  geom_bar(position = "stack", stat = "identity")+
  scale_fill_manual(values = col_w)+
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, size=18, hjust=1, vjust=0.5)) +
  ggtitle("")+
  guide_italics+
  theme(legend.title = element_text(size = 20),
        legend.position="bottom",
        legend.text = element_text(size=14),
        panel.spacing.y=unit(1, "lines"),
        panel.spacing.x=unit(0.8, "lines"),
        panel.spacing=unit(0,"lines"),
        strip.background=element_rect(color="grey30", fill="grey90"),
        strip.text.x = element_text(size = 18),
        panel.border=element_rect(color="grey90"),
        axis.ticks.x=element_blank(),
        axis.text.y = element_text(size=18)) +
  facet_wrap(~Species.x+Strain+Organ, scales = "free", ncol=3, labeller=label_parsed)+
  labs(x="Sample", y="Relative abundance", fill="Oligotype / MED node")

p
```

## Ovary (the 15 most abundant nodes)
```{r fig.height = 12, fig.width=18}
# data pour plot
#data_for_plot2 <- taxo_data(ps.filter.ovary, method = "abundance", top=15, other=FALSE)
data_for_plot2 <- taxo_data(ps.filter.ovary, top=15)
paste0("\n15 MOST ABUNDANT GENUS: \n") %>% cat()
paste0("\"", levels(data_for_plot2$Name), "\",\n") %>% cat()

new_names_15_o <- c("N0711.Wolbachia",
               "N0241.Wolbachia",
               "N0720.Wolbachia",
               
               "N0019.Wolbachia",
               "N0044.Wolbachia",
               "N0240.Wolbachia",
               "N0242.Wolbachia",
               "N0244.Wolbachia",
               "N0245.Wolbachia",
               "N0250.Wolbachia",
               "N0251.Wolbachia",
               "N0712.Wolbachia",
               "N0714.Wolbachia",
               "N0715.Wolbachia",
               
               "N1147.Asaia",
               "Other")
data_for_plot2$Name <- factor(data_for_plot2$Name, levels = new_names_15_o)

levels(data_for_plot2$Species.x)= c("Aedes aegypti"=make.italic("Aedes aegypti"),
               "Culex pipiens"=make.italic("Culex pipiens"),
               "Culex quinquefasciatus"=make.italic("Culex quinquefasciatus"))

levels(data_for_plot2$Strain) <- c("Field - Bosc", 
                                  "Field~-~Camping~Europe", 
                                  "Field~-~Guadeloupe", 
                                  "Laboratory~-~Lavar", 
                                  expression(paste("Laboratory - Slab TC (", italic("Wolbachia"), "-)")))

p2 <- ggplot(data_for_plot2, aes(x = Sample, y = Relative_Abundance, fill = Name, species=Species.x, organ=Organ, Strain=Strain))+ 
  geom_bar(position = "stack", stat = "identity")+
  scale_fill_manual(values = col_o)+
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, size=18, hjust=1, vjust=0.5)) +
  ggtitle("")+
  guide_italics+
  theme(legend.title = element_text(size = 20),
        legend.position="bottom",
        legend.text = element_text(size=14),
        panel.spacing.y=unit(1, "lines"),
        panel.spacing.x=unit(0.8, "lines"),
        panel.spacing=unit(0,"lines"),
        strip.background=element_rect(color="grey30", fill="grey90"),
        strip.text.x = element_text(size = 18),
        panel.border=element_rect(color="grey90"),
        axis.ticks.x=element_blank(),
        axis.text.y = element_text(size=18)) +
  facet_wrap(~Species.x+Strain+Organ, scales = "free", ncol=3, labeller=label_parsed)+
  labs(x="Sample", y="Relative abundance", fill="Oligotype / MED node")

p2
```



# Save plots
```{r warning=FALSE}
png("../../../../output/1_MED/1E/1Ee_MED_15_taxonomic_whole.png", units="in", width=16, height=12, res=300)
p
dev.off()

png("../../../../output/1_MED/1E/1Ee_MED_15_taxonomic_ovary.png", units="in", width=14, height=12, res=300)
p2
dev.off()

tiff("../../../../output/1_MED/1E/1Ee_MED_15_taxonomic_whole.png", units="in", width=16, height=12, res=300)
p
dev.off()

tiff("../../../../output/1_MED/1E/1Ee_MED_15_taxonomic_ovary.png", units="in", width=14, height=12, res=300)
p2
dev.off()
```

# Session info
```{r warning=FALSE, message=FALSE}
sessionInfo()
```


```{r eval=FALSE, include=FALSE}
## % of Wolbachia in Aedes aegypti samples
# ps.filter.whole.aedes <- ps.filter.whole %>% subset_samples(Species=="Aedes aegypti")
#   ps_global <- transform_sample_counts(ps.filter.whole.aedes, function(x) x / sum(x))
# 
#   # melt phyloseq object
#   data_for_plot <- psmelt(ps_global)
# 
#   # add a column with custom name for oligotypes
#   data_for_plot$Name <- paste(data_for_plot$OTU,data_for_plot$Genus, sep=".")
# 
#   # convert Name column to factor
#   data_for_plot$Name <- as.factor(data_for_plot$Name)
# 
#   # replace Abundance column name to "Relative_Abundance"
#   colnames(data_for_plot)[colnames(data_for_plot) %in% "Abundance"] <- "Relative_Abundance"
# 
#   # replace name of Species column by "Species.x" to avoid duplication
#   colnames(data_for_plot)[colnames(data_for_plot) %in% "sample_Species"] <- "Species.x"
# 
#   data2 <- data_for_plot %>% select(c(Sample, Relative_Abundance, Genus))
#   test2 <- reshape(data2, idvar = c("Genus"), timevar = "Sample", direction="wide") %>% data.frame()
#   values <- test2[5,c(2:10)] %>% sort()
```